
sbatch ${SCRIPT_PATH} "GPpsy" 
sbatch ${SCRIPT_PATH} "DepAll" 
sbatch ${SCRIPT_PATH} "ICD10Dep" 
sbatch ${SCRIPT_PATH} "LifetimeMDD" 
sbatch ${SCRIPT_PATH} "Psypsy" 
sbatch ${SCRIPT_PATH} "DepAll" 

sbatch ${SCRIPT_PATH} "LifetimeMDD_imputed" sbatch ${SCRIPT_PATH} "ICD10Dep_imputed" 
sbatch ${SCRIPT_PATH} "GPpsy_imputed" 
sbatch ${SCRIPT_PATH} "Psypsy_imputed" 
sbatch ${SCRIPT_PATH} "DepAll_imputed" 
sbatch ${SCRIPT_PATH} "DepAll" 
sbatch ${SCRIPT_PATH} "Psypsy" 
sbatch ${SCRIPT_PATH} "LifetimeMDD" 
sbatch ${SCRIPT_PATH} "ICD10Dep" 
sbatch ${SCRIPT_PATH} "GPpsy" 